// Cedarville program → department → school.
//
// Scraped from cedarville.edu/academic-programs, which tags every program with
// a department, plus cedarville.edu/academic-schools-and-departments for the
// school each department sits under. Ambiguous tags (Criminal Justice,
// Linguistics, Media Production, International Studies, Visual Communication
// Design) were each confirmed against their own program page.
//
// One wrinkle worth knowing: the tag cedarville.edu attaches to a program is a
// department for majors but the PARENT PROGRAM for concentrations — "TESOL" is
// tagged Linguistics because it is a track inside the Linguistics major, not
// because a Linguistics department exists. School resolution is unaffected,
// since both kinds of tag land in the same school, but do not read the middle
// column as an org chart.
//
// None of this comes from the directory scrape; it is public catalog data.

export const SCHOOLS = {
  AHP: "School of Allied Health and Psychology",
  AH: "School of Arts and Humanities",
  BTS: "School of Biblical and Theological Studies",
  BUS: "Robert W. Plaster School of Business",
  ESW: "School of Education and Social Work",
  ECS: "School of Engineering and Computer Science",
  NUR: "School of Nursing",
  PHA: "School of Pharmacy",
  SM: "School of Science and Mathematics",
  INT: "School of Interdisciplinary Studies",
  ROTC: "Military Science (ROTC)",
};

export const DEPARTMENT_SCHOOL = {
  Accounting: "BUS",
  "Allied Health": "AHP",
  "Art, Design, and Theatre": "AH",
  "Arts and Humanities": "AH",
  "Biblical and Theological Studies": "BTS",
  Biology: "SM",
  Business: "BUS",
  Chemistry: "SM",
  "Civil Engineering": "ECS",
  Communication: "BUS",
  "Computer Engineering": "ECS",
  "Computer Science": "ECS",
  "Criminal Justice": "AH",
  "Cyber Operations": "ECS",
  Economics: "BUS",
  Education: "ESW",
  "Electrical Engineering": "ECS",
  Engineering: "ECS",
  "English, Literature, and Modern Languages": "AH",
  "Environmental Science": "SM",
  Finance: "BUS",
  Geology: "SM",
  "History and Government": "AH",
  "Information Technology Management": "BUS",
  Interdisciplinary: "INT",
  "Interdisciplinary Studies": "INT",
  "International Studies": "AH",
  Linguistics: "AH",
  Management: "BUS",
  Mathematics: "SM",
  "Media Production": "BUS",
  "Military Science": "ROTC",
  "Modern Languages": "AH",
  "Music and Worship": "AH",
  Nursing: "NUR",
  Pharmacy: "PHA",
  Physics: "SM",
  Psychology: "AHP",
  "Science and Mathematics": "SM",
  "Social Work": "ESW",
  "Sport Medicine": "AHP",
  "Visual Communication Design": "AH",
};

// [program, department]. A program appears more than once when the catalog
// genuinely lists it under more than one parent, e.g. Geology is both its own
// major and an Environmental Science track.
export const PROGRAMS = [
  ["Accounting", "Accounting"],
  ["Accounting Minor", "Accounting"],
  ["Actuarial Science Minor", "Mathematics"],
  ["Addictions and Chemical Dependency", "Psychology"],
  ["Addictions and Chemical Dependency Minor", "Psychology"],
  ["Advocacy Communication", "Communication"],
  ["Agricultural Business", "Biology"],
  ["Allied Health", "Allied Health"],
  ["Animal and Wildlife Biology", "Environmental Science"],
  ["Artificial Intelligence", "Computer Science"],
  ["Artificial Intelligence", "Cyber Operations"],
  ["Asian Studies Minor", "History and Government"],
  ["Athletic Training", "Sport Medicine"],
  ["Audio", "Media Production"],
  ["Bible Minor", "Biblical and Theological Studies"],
  ["Bible Teacher Education Minor", "Biblical and Theological Studies"],
  ["Biblical and Theological Studies", "Biblical and Theological Studies"],
  ["Biblical and Theological Studies (BA + MTS)", "Biblical and Theological Studies"],
  ["Biblical and Theological Studies (Graduate Certificate)", "Biblical and Theological Studies"],
  ["Biblical Care and Counseling Minor", "Biblical and Theological Studies"],
  ["Biblical Counseling", "Biblical and Theological Studies"],
  ["Biblical Counseling (Graduate Certificate)", "Biblical and Theological Studies"],
  ["Biblical Languages", "Biblical and Theological Studies"],
  ["Biblical Languages", "Linguistics"],
  ["Biblical Literature", "Biblical and Theological Studies"],
  ["Biblical Studies", "Biblical and Theological Studies"],
  ["Biology", "Biology"],
  ["Biology Minor", "Biology"],
  ["Biomedical Engineering Minor", "Engineering"],
  ["British Studies Minor", "Art, Design, and Theatre"],
  ["Broadcasting and Digital Media Minor", "Communication"],
  ["Business Administration Minor", "Business"],
  ["Business Analyst", "Information Technology Management"],
  ["Business Analytics (Graduate Certificate)", "Business"],
  ["Business Analytics Minor", "Business"],
  ["Certificate in Medical Spanish Program", "Modern Languages"],
  ["Chemistry", "Chemistry"],
  ["Chemistry Education", "Chemistry"],
  ["Chemistry Minor", "Chemistry"],
  ["Child and Family Studies", "Psychology"],
  ["Child and Family Studies Minor", "Psychology"],
  ["Christian Ministry Minor", "Biblical and Theological Studies"],
  ["Church History Minor", "Biblical and Theological Studies"],
  ["Civil Engineering", "Engineering"],
  ["Communication", "Communication"],
  ["Community Development", "Environmental Science"],
  ["Comprehensive Communication Arts Minor", "Communication"],
  ["Comprehensive Counseling", "Psychology"],
  ["Comprehensive Counseling Minor", "Psychology"],
  ["Computer Engineering", "Engineering"],
  ["Computer Science", "Computer Science"],
  ["Computer Science Minor", "Computer Science"],
  ["Construction Management", "Management"],
  ["Construction Management Minor", "Management"],
  ["CPA", "Accounting"],
  ["Creative Writing", "English, Literature, and Modern Languages"],
  ["Creative Writing Minor", "English, Literature, and Modern Languages"],
  ["Criminal Justice", "Criminal Justice"],
  ["Criminal Justice Minor", "Criminal Justice"],
  ["Cross-Cultural Nursing", "Nursing"],
  ["Cross-Cultural Psychology", "Psychology"],
  ["Cross-Cultural Psychology Minor", "Psychology"],
  ["Cultural Studies", "Linguistics"],
  ["Cyber Management", "Information Technology Management"],
  ["Cyber Operations", "Computer Science"],
  ["Cybersecurity Management (Graduate Certificate)", "Business"],
  ["Data Analyst", "Information Technology Management"],
  ["Data Science/Artificial Intelligence", "Computer Engineering"],
  ["Data Science/Artificial Intelligence", "Electrical Engineering"],
  ["Data Science/Artificial Intelligence", "Mathematics"],
  ["Data Science/Artificial Intelligence", "Physics"],
  ["Digital Marketing Strategy (Graduate Certificate)", "Communication"],
  ["Digital Systems", "Electrical Engineering"],
  ["Digital Video Minor", "Media Production"],
  ["DNP, Adult-Gerontology Acute Care Nurse Practitioner", "Nursing"],
  ["DNP, Doctor of Nursing Practice", "Nursing"],
  ["DNP, Family Nurse Practitioner", "Nursing"],
  ["DNP, Nursing Leadership in Healthcare Improvement", "Nursing"],
  ["DNP, Pediatric Nurse Practitioner", "Nursing"],
  ["Earth Science Minor", "Science and Mathematics"],
  ["Ecology", "Biology"],
  ["Economics", "Economics"],
  ["Economics Minor", "Economics"],
  ["Editing and Publishing Minor", "English, Literature, and Modern Languages"],
  ["Education and Psychology", "Linguistics"],
  ["Electrical Engineering", "Engineering"],
  ["EMS Education", "Allied Health"],
  ["English", "English, Literature, and Modern Languages"],
  ["English and Writing", "Linguistics"],
  ["Entrepreneurship", "Management"],
  ["Entrepreneurship Minor", "Management"],
  ["Environmental Communication", "Environmental Science"],
  ["Environmental Engineering", "Civil Engineering"],
  ["Environmental Law and Policy", "Environmental Science"],
  ["Environmental Science", "Environmental Science"],
  ["Exercise Science", "Allied Health"],
  ["Field Ecology", "Environmental Science"],
  ["Film and Video", "Media Production"],
  ["Finance", "Finance"],
  ["Financial Planning Minor", "Finance"],
  ["Forensic Science", "Science and Mathematics"],
  ["French Minor", "Modern Languages"],
  ["Geology", "Geology"],
  ["Geology", "Environmental Science"],
  ["Geology Minor", "Geology"],
  ["Global Engagement", "Linguistics"],
  ["Global Public Health (Graduate Certificate)", "Allied Health"],
  ["Graphic Design", "Visual Communication Design"],
  ["Graphic Design Minor", "Art, Design, and Theatre"],
  ["Greek Minor", "Biblical and Theological Studies"],
  ["Hardware", "Computer Science"],
  ["Health Psychology and Public Health", "Psychology"],
  ["Health Psychology and Public Health Minor", "Psychology"],
  ["Healthcare Management (Graduate Certificate)", "Business"],
  ["Historical Theology", "Biblical and Theological Studies"],
  ["History", "History and Government"],
  ["History Minor", "History and Government"],
  ["Honors Program", "Interdisciplinary"],
  ["Human Resource Management", "Management"],
  ["Individualized Studies", "Interdisciplinary Studies"],
  ["Industrial and Innovative Design", "Art, Design, and Theatre"],
  ["Information Technology Management", "Information Technology Management"],
  ["Information Technology Management Minor", "Information Technology Management"],
  ["Innovation and Entrepreneurship", "Business"],
  ["Interactive Web Design", "Visual Communication Design"],
  ["Interactive Web Design Minor", "Art, Design, and Theatre"],
  ["Intercultural Communication Minor", "Communication"],
  ["International Business", "Management"],
  ["International Business Minor", "Business"],
  ["International Infrastructure Engineering", "Civil Engineering"],
  ["International Studies", "International Studies"],
  ["International Studies Minor", "International Studies"],
  ["Jazz and Improvisation", "Music and Worship"],
  ["Keyboard Pedagogy", "Music and Worship"],
  ["Language Arts Education - Integrated", "Education"],
  ["Latin American Studies Minor", "History and Government"],
  ["Leadership (Graduate Certificate)", "Business"],
  ["Liberal Arts", "Arts and Humanities"],
  ["Life Science Education", "Education"],
  ["Linguistics", "Linguistics"],
  ["Linguistics Minor", "Linguistics"],
  ["Literary Studies", "English, Literature, and Modern Languages"],
  ["Literature Minor", "English, Literature, and Modern Languages"],
  ["MACOL, Communication and Organizational Leadership", "Communication"],
  ["MACOL, Digital Communication and Marketing", "Communication"],
  ["MACOL, Healthcare Management", "Business"],
  ["MACOL, Professional Leadership", "Communication"],
  ["MACOL, Social Media and Cybersecurity Management", "Communication"],
  ["Management", "Management"],
  ["Marketing", "Business"],
  ["Marketing Minor", "Business"],
  ["MASI, Business Analytics and Visualization", "Business"],
  ["MASI, Business Innovation", "Business"],
  ["MASI, Healthcare Innovation", "Business"],
  ["MASI, Strategic Innovation", "Business"],
  ["MAT, Athletic Training", "Sport Medicine"],
  ["Mathematics", "Mathematics"],
  ["Mathematics Education - Integrated", "Education"],
  ["Mathematics Minor", "Mathematics"],
  ["MBA, Accounting", "Business"],
  ["MBA, Business Administration", "Business"],
  ["MBA, Business Analytics", "Business"],
  ["MBA, Cybersecurity Management", "Business"],
  ["MBA, Healthcare Management", "Business"],
  ["MBA, Nursing Leadership", "Business"],
  ["MBA, Operations Management", "Business"],
  ["MBA, Strategic Innovation and Entrepreneurship", "Business"],
  ["MDiv + MBA", "Biblical and Theological Studies"],
  ["MDiv, Accelerated (BA + MDiv)", "Biblical and Theological Studies"],
  ["MDiv, Advanced", "Biblical and Theological Studies"],
  ["MDiv, Bible Translation", "Biblical and Theological Studies"],
  ["MDiv, Biblical and Theological Studies Research", "Biblical and Theological Studies"],
  ["MDiv, Biblical Care and Counseling", "Biblical and Theological Studies"],
  ["MDiv, Church Planting and Revitalization", "Biblical and Theological Studies"],
  ["MDiv, Master of Divinity", "Biblical and Theological Studies"],
  ["MDiv, Ministry Leadership", "Biblical and Theological Studies"],
  ["MDiv, Missions", "Biblical and Theological Studies"],
  ["MDiv, Pastoral Leadership", "Biblical and Theological Studies"],
  ["MDiv, Women's Ministry", "Biblical and Theological Studies"],
  ["MDiv, Worship and Theology", "Biblical and Theological Studies"],
  ["MDiv, Youth and Family", "Biblical and Theological Studies"],
  ["Mechanical Engineering", "Engineering"],
  ["Media Production", "Media Production"],
  ["Middle Childhood Education", "Education"],
  ["Middle Eastern Studies Minor", "History and Government"],
  ["Military History Minor", "History and Government"],
  ["Missions", "Biblical and Theological Studies"],
  ["Missions Minor", "Biblical and Theological Studies"],
  ["MMSc-PA, Physician Assistant (PA) Studies", "Allied Health"],
  ["Modern Languages", "Linguistics"],
  ["Molecular Biology", "Biology"],
  ["Molecular Ecology", "Environmental Science"],
  ["Motion Design", "Media Production"],
  ["Motion Graphics Minor", "Art, Design, and Theatre"],
  ["MSN + MBA", "Nursing"],
  ["MSN, Adult-Gerontology Acute Care Nurse Practitioner", "Nursing"],
  ["MSN, Family Nurse Practitioner", "Nursing"],
  ["MSN, Master of Science in Nursing", "Nursing"],
  ["MSN, Nurse Educator", "Nursing"],
  ["MSN, Nursing Leadership in Healthcare Improvement", "Nursing"],
  ["MSN, Pediatric Nurse Practitioner", "Nursing"],
  ["MTS, Biblical Counseling", "Biblical and Theological Studies"],
  ["MTS, Biblical Leadership", "Biblical and Theological Studies"],
  ["MTS, Master of Theological Studies", "Biblical and Theological Studies"],
  ["MTS, Ministry", "Biblical and Theological Studies"],
  ["MTS, Worship and Theology", "Biblical and Theological Studies"],
  ["Music", "Music and Worship"],
  ["Music Composition", "Music and Worship"],
  ["Music Education - Multi-Age", "Music and Worship"],
  ["Music Minor", "Music and Worship"],
  ["Music Performance", "Music and Worship"],
  ["Music Technology Minor", "Music and Worship"],
  ["National Security Minor", "History and Government"],
  ["Neuropsychology", "Psychology"],
  ["Neuropsychology Minor", "Psychology"],
  ["Nursing", "Nursing"],
  ["Nursing Education (Graduate Certificate)", "Nursing"],
  ["Nursing Leadership (Graduate Certificate)", "Nursing"],
  ["Occupational Therapy", "Psychology"],
  ["One-Year Bible Program", "Biblical and Theological Studies"],
  ["Operations Management", "Management"],
  ["Operations Management (Graduate Certificate)", "Business"],
  ["Organizational Communication", "Communication"],
  ["Organizational Communication Minor", "Communication"],
  ["Performance Studies - Instrumental", "Music and Worship"],
  ["Performance Studies - Voice", "Music and Worship"],
  ["Pharmaceutical Sciences", "Pharmacy"],
  ["PharmD + MASI", "Pharmacy"],
  ["PharmD + MBA", "Pharmacy"],
  ["PharmD, Doctor of Pharmacy", "Pharmacy"],
  ["Philosophy and Theology", "Biblical and Theological Studies"],
  ["Philosophy and Theology Minor", "Biblical and Theological Studies"],
  ["Physical Science Education", "Education"],
  ["Physics", "Physics"],
  ["Physics Education", "Physics"],
  ["Physics Minor", "Physics"],
  ["Plant and Agricultural Science", "Biology"],
  ["Plant and Agricultural Science", "Environmental Science"],
  ["Political Science", "History and Government"],
  ["Political Science Minor", "History and Government"],
  ["Power and Energy", "Electrical Engineering"],
  ["Pre-Chiropractic", "Allied Health"],
  ["Predental", "Allied Health"],
  ["Prelaw", "History and Government"],
  ["Pre-Master of Divinity Minor", "Biblical and Theological Studies"],
  ["Premedical", "Allied Health"],
  ["Premedical Sciences", "Biology"],
  ["Pre-Occupational Therapy", "Allied Health"],
  ["Preoptometric", "Allied Health"],
  ["Preparation for Health Professions", "Allied Health"],
  ["Pre-Physical Therapy", "Allied Health"],
  ["Pre-Physician Assistant", "Allied Health"],
  ["Pre-Physician Assistant", "Biology"],
  ["Preseminary Minor", "Biblical and Theological Studies"],
  ["Pre-Speech Therapy", "Linguistics"],
  ["Pre-Veterinary", "Biology"],
  ["Primary (P-5) + Special Education", "Education"],
  ["Primary (P-5) Education", "Education"],
  ["Professional Writing and Information Design", "English, Literature, and Modern Languages"],
  ["Psychological Research Minor", "Psychology"],
  ["Psychology", "Psychology"],
  ["Psychology Minor", "Psychology"],
  ["Psychology Research", "Psychology"],
  ["Public Administration Minor", "History and Government"],
  ["Public Policy Minor", "History and Government"],
  ["ROTC", "Military Science"],
  ["Science Comprehensive Education - Integrated", "Education"],
  ["Signal/Image Processing", "Electrical Engineering"],
  ["Social Studies Education - Integrated", "Education"],
  ["Social Work", "Social Work"],
  ["Sociology Minor", "Social Work"],
  ["Songwriting Minor", "Music and Worship"],
  ["Spanish", "Modern Languages"],
  ["Spanish Education (Multi-Age)", "Modern Languages"],
  ["Spanish for Healthcare Personnel Minor", "Modern Languages"],
  ["Spanish for Professionals Minor", "Modern Languages"],
  ["Spanish Minor", "Modern Languages"],
  ["Special Education", "Education"],
  ["Sport Business Management", "Business"],
  ["Sport Management Minor", "Business"],
  ["Sport Medicine", "Sport Medicine"],
  ["Sports Media", "Media Production"],
  ["Strategic Communication", "Communication"],
  ["Structural Engineering", "Civil Engineering"],
  ["Studio Art", "Art, Design, and Theatre"],
  ["Studio Art Minor", "Art, Design, and Theatre"],
  ["Teaching English to Speakers of Other Languages Minor", "Linguistics"],
  ["Teaching Ministry", "Biblical and Theological Studies"],
  ["TESOL", "Linguistics"],
  ["Theatre", "Art, Design, and Theatre"],
  ["Theatre Minor", "Art, Design, and Theatre"],
  ["Theatre Performance Minor", "Art, Design, and Theatre"],
  ["Theology", "Biblical and Theological Studies"],
  ["Video Game Engineering", "Computer Science"],
  ["Visual Communication Design", "Visual Communication Design"],
  ["Water Resources Engineering", "Civil Engineering"],
  ["Western European Studies Minor", "History and Government"],
  ["Women's Ministry", "Biblical and Theological Studies"],
  ["Women's Ministry Minor", "Biblical and Theological Studies"],
  ["Worship", "Music and Worship"],
  ["Worship Leadership (Graduate Certificate)", "Music and Worship"],
  ["Worship Minor", "Music and Worship"],
  ["Writing for the Professions Minor", "English, Literature, and Modern Languages"],
  ["Writing Studies", "English, Literature, and Modern Languages"],
  ["Youth and Family Ministry", "Biblical and Theological Studies"],
  ["Youth and Family Ministry Minor", "Biblical and Theological Studies"],
  ["Zoology", "Biology"],
];

const GRADUATE_PREFIX = /^(MBA|MSN|MDiv|MTS|MACOL|MASI|MAT|DNP|PharmD|MMSc-PA)\b/;

export function levelOf(program) {
  if (/\(Graduate Certificate\)$/.test(program)) return "certificate";
  if (/ Minor$/.test(program)) return "minor";
  if (GRADUATE_PREFIX.test(program) || /^Pharmaceutical Sciences$/.test(program))
    return "graduate";
  if (/^(Pre-|Pre[a-z])/.test(program)) return "pre-professional";
  return "major";
}

const byName = new Map();
for (const [program, department] of PROGRAMS) {
  if (!byName.has(program)) byName.set(program, []);
  byName.get(program).push(department);
}

export const departmentsOf = (program) => byName.get(program) ?? [];
export const departmentOf = (program) => departmentsOf(program)[0] ?? "";

// Every one of the 42 departments belongs to exactly one school, so a
// department always resolves cleanly. Program names do not: three of them are
// concentrations offered inside majors that sit in different schools, so this
// returns every school the name touches.
export const schoolsOf = (program) => [
  ...new Set(
    departmentsOf(program)
      .map((d) => SCHOOLS[DEPARTMENT_SCHOOL[d]])
      .filter(Boolean),
  ),
];

export const isAmbiguous = (program) => schoolsOf(program).length > 1;

// The single best answer, which for an ambiguous program is only the first
// listing — check isAmbiguous first if that matters.
export const schoolOf = (program) => schoolsOf(program)[0] ?? "";
